In [1]:
import numpy as np

In [6]:
P = np.array([
    [0,0.5,0.5,0],
    [0.5,0,0.5,0],
    [0.4,0,0,0.6],
    [0,0.2,0.6,0.2]])
P

array([[0. , 0.5, 0.5, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0.4, 0. , 0. , 0.6],
       [0. , 0.2, 0.6, 0.2]])

In [7]:
P.sum(axis=1)

array([1., 1., 1., 1.])

In [13]:
p0 = np.array([.25,.25,.25,.25])
p0

array([0.25, 0.25, 0.25, 0.25])

### test

In [8]:
np.linalg.matrix_power(P, 2)

array([[0.45, 0.  , 0.25, 0.3 ],
       [0.2 , 0.25, 0.25, 0.3 ],
       [0.  , 0.32, 0.56, 0.12],
       [0.34, 0.04, 0.22, 0.4 ]])

In [9]:
P@P

array([[0.45, 0.  , 0.25, 0.3 ],
       [0.2 , 0.25, 0.25, 0.3 ],
       [0.  , 0.32, 0.56, 0.12],
       [0.34, 0.04, 0.22, 0.4 ]])

In [10]:
np.linalg.matrix_power(P, 3)

array([[0.1  , 0.285, 0.405, 0.21 ],
       [0.225, 0.16 , 0.405, 0.21 ],
       [0.384, 0.024, 0.232, 0.36 ],
       [0.108, 0.25 , 0.43 , 0.212]])

In [11]:
P@P@P

array([[0.1  , 0.285, 0.405, 0.21 ],
       [0.225, 0.16 , 0.405, 0.21 ],
       [0.384, 0.024, 0.232, 0.36 ],
       [0.108, 0.25 , 0.43 , 0.212]])

### continue

In [15]:
(p0@np.linalg.matrix_power(P, 3))[3]

0.248

### $P(X_3=s,X_5=s,X_6=p) = (\pi^0P^3)_s*P_{ss}^2*P_{sp}$

In [17]:
(p0@np.linalg.matrix_power(P, 3))[3]*np.linalg.matrix_power(P, 2)[3,3]*P[3,2]

0.059519999999999997

### Example 2

In [21]:
P = np.array([
    [0.1,0.2,0.5,0.2],
    [0.5,0,0.3,0.2],
    [0.2,0.2,0,0.6],
    [0.1,0.2,0.5,0.2]])
print(np.array(['b','f','p','s']))
print(P.sum(axis=1)) 
P

['b' 'f' 'p' 's']
[1. 1. 1. 1.]


array([[0.1, 0.2, 0.5, 0.2],
       [0.5, 0. , 0.3, 0.2],
       [0.2, 0.2, 0. , 0.6],
       [0.1, 0.2, 0.5, 0.2]])

### $P(X_4=s,X_9=b,X_{30}=p) = (\pi^0P^4)_s*P_{sb}^5*P_{bp}^{21}$

In [22]:
(p0@np.linalg.matrix_power(P, 4))[3]*np.linalg.matrix_power(P, 5)[3,0]*np.linalg.matrix_power(P, 21)[0,2]

0.019715666758712273

### $P(X_4=s,X_9=(b \lor p),X_{30}=(p\lor s)) = (\pi^0P^4)_s*(P_{sb}^5+P_{sp}^5)*(P_{bp}^{21}+P_{bs}^{21}+P_{pp}^{21}+P_{ps}^{21})$

In [40]:
a = (p0@np.linalg.matrix_power(P, 4))[3]
a

0.32489999999999997

In [42]:
b = np.linalg.matrix_power(P, 5)[3,0] + np.linalg.matrix_power(P, 5)[3,2]
b

0.51932

In [26]:
np.linalg.matrix_power(P, 21) # ESTAS SON PROBABILIDADES NO CONDICIONADAS

array([[0.19777774, 0.16666667, 0.31111131, 0.32444428],
       [0.1977778 , 0.16666667, 0.31111099, 0.32444454],
       [0.19777783, 0.16666667, 0.31111084, 0.32444466],
       [0.19777774, 0.16666667, 0.31111131, 0.32444428]])

In [27]:
np.linalg.matrix_power(P, 21)[0,2] , np.linalg.matrix_power(P, 21)[0,3] , np.linalg.matrix_power(P, 21)[2,2] , np.linalg.matrix_power(P, 21)[2,3]

(0.31111131244235535,
 0.3244442833794492,
 0.31111083560519714,
 0.3244446648491757)

In [43]:
c = np.linalg.matrix_power(P, 21)[0,2] + np.linalg.matrix_power(P, 21)[0,3] + np.linalg.matrix_power(P, 21)[2,2] + np.linalg.matrix_power(P, 21)[2,3]
c

1.2711110962761774

In [49]:
(a,b,c),a*b*c 

((0.32489999999999997, 0.51932, 1.2711110962761774), 0.2144708483769451)

In [47]:
np.linalg.matrix_power(P, 5)

array([[0.19505, 0.16672, 0.32427, 0.31396],
       [0.19975, 0.1664 , 0.30365, 0.3302 ],
       [0.2013 , 0.16672, 0.29302, 0.33896],
       [0.19505, 0.16672, 0.32427, 0.31396]])

In [46]:
np.linalg.matrix_power(P, 5)[3,0]*a, np.linalg.matrix_power(P, 5)[3,2]*a

(0.06337174500000001, 0.10535532299999997)

In [48]:
(np.linalg.matrix_power(P, 5)[3,0] + np.linalg.matrix_power(P, 5)[3,2])*a

0.16872706799999998

In [50]:
np.linalg.matrix_power(P, 21)[0,2]*np.linalg.matrix_power(P, 5)[3,0]*a , np.linalg.matrix_power(P, 21)[0,3]*np.linalg.matrix_power(P, 5)[3,0]*a

(0.01971566675871227, 0.020560600393030194)

In [51]:
np.linalg.matrix_power(P, 21)[2,2]*np.linalg.matrix_power(P, 5)[3,2]*a , np.linalg.matrix_power(P, 21)[2,3]*np.linalg.matrix_power(P, 5)[3,2]*a

(0.03277718257398544, 0.034181972460811644)

In [ ]:
(p0@np.linalg.matrix_power(P, 4))[3]*np.linalg.matrix_power(P, 5)[3,0]*np.linalg.matrix_power(P, 21)[0,2]

### 4 paths

In [54]:
sbps = (p0@np.linalg.matrix_power(P, 4))[3]*np.linalg.matrix_power(P, 5)[3,0]*(np.linalg.matrix_power(P, 5)[0,2] + np.linalg.matrix_power(P, 5)[0,3])
sbps

0.040445748811350005

In [55]:
spps = (p0@np.linalg.matrix_power(P, 4))[3]*np.linalg.matrix_power(P, 5)[3,2]*(np.linalg.matrix_power(P, 5)[2,2] + np.linalg.matrix_power(P, 5)[2,3])
spps

0.06658245702953998

In [56]:
sbps+spps

0.10702820584088998