In [1]:
import numpy as np

In [7]:
A = np.array([[1,2,6],
             [1/2,1,4],
              [1/6,1/4,1]])

### Relative Weigth

In [13]:
Csum = A.sum(axis=0)
Csum

array([ 1.66666667,  3.25      , 11.        ])

In [14]:
R = A/Csum
R

array([[0.6       , 0.61538462, 0.54545455],
       [0.3       , 0.30769231, 0.36363636],
       [0.1       , 0.07692308, 0.09090909]])

In [15]:
Rsum = R.sum(axis=1)
Rsum

array([1.76083916, 0.97132867, 0.26783217])

In [16]:
eig = Rsum/len(A)
eig

array([0.58694639, 0.32377622, 0.08927739])

### Consistency Ratio

In [27]:
V = A@eig
V

array([1.77016317, 0.97435897, 0.26804584])

In [28]:
P = V/eig
P

array([3.01588562, 3.00935925, 3.00239339])

In [29]:
eigVal = P.sum()/len(A)
eigVal

3.009212753441092

In [30]:
cIndex = (eigVal - len(A))/ (len(A)-1)
cIndex

0.004606376720545979

In [ ]:
#cRatio = 

### SAATYs Approximation

In [41]:
A = np.array([[1,2/5],
             [5, 1]])
A

array([[1. , 0.4],
       [5. , 1. ]])

In [42]:
# Aw = Lw ==> (A-LI)w=0
Csum = A.sum(axis=0)
Csum

array([6. , 1.4])

In [43]:
A/Csum

array([[0.16666667, 0.28571429],
       [0.83333333, 0.71428571]])

In [49]:
print('     w1,   w2')
np.mean(A/Csum, axis=1)

     w1,   w2


array([0.22619048, 0.77380952])

In [50]:
def saaty(A):
    Csum = A.sum(axis=0)
    W = np.mean(A/Csum, 0)
    
    return W
    

In [53]:
A = np.array([[1,1/4,1/4],
             [3,1,1/3],
             [4,2,1],
             ]) 

saaty(A)

array([0.33333333, 0.33333333, 0.33333333])

In [70]:
from scipy.optimize import minimize, minimize_scalar

In [77]:
def objective_function_test(v):
    (a, b, R) = v
    
    loss = np.square(a + b*np.exp(-80000/R) - 1) 
    loss += np.square(a + b*np.exp(-50000/R) - 0.5)
    loss += np.square(a + b*np.exp(-40000/R) - 0)  
        
    return loss

In [78]:
res = minimize(objective_function_test, x0 = (1,1,1000))
res

      fun: 0.5
 hess_inv: array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])
      jac: array([7.4505806e-08, 0.0000000e+00, 0.0000000e+00])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 1
     njev: 3
   status: 0
  success: True
        x: array([5.00000004e-01, 1.00000000e+00, 1.00000000e+03])